# Generated by Django 2.1 on 2018-09-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobjars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.CharField(max_length=250)),
                ('task_value', models.TextField()),
                ('task_minAge', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
