# Generated by Django 2.1 on 2018-09-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobjars', '0002_auto_20180905_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('completed_time', models.TimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobjars.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_first_name', models.CharField(max_length=100)),
                ('person_last_name', models.CharField(max_length=100)),
                ('person_parent', models.BooleanField(null=True)),
                ('person_child', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='completedtasks',
            name='task_approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobjars.Person'),
        ),
        migrations.AddField(
            model_name='completedtasks',
            name='task_completed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='completed_by', to='jobjars.Person'),
        ),
    ]
